name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: "waka_66eb96fa-11ed-4cda-910b-aa2c6977537a"
          GH_TOKEN: "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"
